global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'Local'

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node_exporter'
      type: 'A'
      port: 9100
